### ISSUE TITLE
Ensure that `z != 0` in batch verification

### ISSUE THREAD

**Issue by str4d** [ZcashFoundation/redjubjub#133]
Appendix B.1 of the Zcash Protocol Spec states that `z` should be a 128-bit random value, excluding zero:
![image](https://user-images.githubusercontent.com/4993799/134249595-da1bf82f-11db-47c0-9132-27277c86edb0.png)

However, currently `z` is sampled like so:
https://github.com/ZcashFoundation/redjubjub/blob/3db05e29f7d9e6a62420b928e83b126b75ee8a44/src/batch.rs#L227
https://github.com/ZcashFoundation/redjubjub/blob/3db05e29f7d9e6a62420b928e83b126b75ee8a44/src/batch.rs#L28-L35

This could potentially sample `z = 0`, which would cause the signature it is used with to be unconditionally considered valid (as the signature would not contribute at all to the batch). The probability of hitting this is low, but not _that_ low (2<sup>-64</sup> per the birthday bound).

The batch verifier should either loop until `z != 0`, or assert that fact (which is less clean, but equally ensures that a full node that hits this case will not accept an invalid signature).

**Comment by daira** [comment]
It's not 2<sup>-64</sup>, it's 2<sup>-128</sup> per signature. It would in practice be fine to allow zero. [BDLSY2012](https://ed25519.cr.yp.to/ed25519-20110926.pdf) ("Fast batch verification" starting on page 16) doesn't exclude zero.

**Comment by str4d** [comment]
Ah yes, I was mis-remembering how the probabilities are calculated (it's all been displaced by circuit-building logic in my brain 😅). In that case, we can leave this as-is, and instead change the spec to state that it's fine to sample `z` in this way.
