### ISSUE TITLE
Please update the digest dependency to 0.10

### ISSUE THREAD

**Issue by daira** [ZcashFoundation/redjubjub#154]
This will help Zcash to avoid duplicate crate versions: https://github.com/zcash/librustzcash/issues/757

**Comment by daira** [comment]
This would be fixed by #140.

**Comment by teor2345** [comment]
@conradoplg @dconnolly just making sure you see this when you get in later today?

**Comment by teor2345** [comment]
I updated PR #140 using dependabot.
