### ISSUE TITLE
Rerandomization in FROST creates an invalid signature

### ISSUE THREAD

**Issue by hhanh00** [ZcashFoundation/redjubjub#62]
In branch `frost-rerandomize`

Rerandomization of the group public key modifies the point
but leaves the bytes unchanged.

```
        for commitment in &signing_package.signing_commitments {
            let lambda_i = gen_lagrange_coeff(commitment.index, &signing_package)?;
            self.group_public.point += commitment.randomizer * lambda_i;
        }
```

The signature is calculated based on incorrect hash H*(T|bytes|msg) since bytes do not match the point.

Tests pass because the verification is also performed using the same bytes.

**Comment by chelseakomlo** [comment]
We have not yet implemented the rerandomization step for FROST, this is something we are working on now. So please consider branch ```frost-rerandomize``` to be unstable.
